# Generated by Django 5.1.4 on 2024-12-11 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0002_rename_user_cart_student_remove_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselanguages',
            name='teacher',
        ),
        migrations.AddField(
            model_name='courselanguages',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_languages', to='cources.teacher'),
            preserve_default=False,
        ),
    ]
