# Generated by Django 5.1.4 on 2024-12-12 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0003_remove_courselanguages_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_ru',
        ),
    ]
