# Generated by Django 5.1.4 on 2024-12-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0004_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses_student', to='cources.student'),
        ),
    ]
