# Generated by Django 5.1.4 on 2024-12-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0006_remove_assignment_students_assignment_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
