# Generated by Django 5.1.4 on 2024-12-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0007_alter_course_created_at_alter_course_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_registered',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_registered',
            field=models.DateField(auto_now=True),
        ),
    ]
