# Generated by Django 5.1.4 on 2024-12-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0008_student_date_registered_teacher_date_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
